functionsDirectory = "C:\\Users\\tomia\\Desktop\\FOLDERS\\Brands\\1.TOMOTO\\tomoto.com.ar\\TOMOTO\\apps\\web\\netlify\\functions"
functionsDirectoryOrigin = "ui"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\tomia\\Desktop\\FOLDERS\\Brands\\1.TOMOTO\\tomoto.com.ar\\TOMOTO\\apps\\web\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\tomia\\Desktop\\FOLDERS\\Brands\\1.TOMOTO\\tomoto.com.ar\\TOMOTO\\apps\\web"
command = "pnpm build"
functions = "C:\\Users\\tomia\\Desktop\\FOLDERS\\Brands\\1.TOMOTO\\tomoto.com.ar\\TOMOTO\\apps\\web\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]